# Generated by Django 5.2 on 2025-05-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_postmodel_likes_postmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
