# Generated by Django 5.2 on 2025-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_postmodel_category_remove_postmodel_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('News', 'News'), ('SocialMedia', 'Social Media'), ('Travel', 'Travel')], default='News', max_length=20),
        ),
    ]
