# Generated by Django 5.2 on 2025-05-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
    ]
