# Generated by Django 5.2 on 2025-05-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_postmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('News', 'News'), ('SocialMedia', 'Social Media'), ('Travel', 'Travel')], default='Gaming', max_length=50),
        ),
    ]
